# Generated by Django 3.2 on 2021-07-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaultprofilepicture.jpeg', null=True, upload_to=''),
        ),
    ]
