# Generated by Django 3.2.3 on 2021-12-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=300)),
            ],
        ),
    ]
