# Generated by Django 3.2 on 2021-06-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_level_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stutor.education_level'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stutor.subject'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='education_level_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stutor.education_level'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subject_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stutor.subject'),
        ),
    ]
