# Generated by Django 3.2 on 2021-10-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
        ('stutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.tutor_account'),
        ),
    ]
