# Generated by Django 3.2 on 2021-07-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20210712_1731'),
        ('student', '0002_auto_20210712_1731'),
        ('stutor', '0002_alter_tutor_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student_account'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.tutor_account'),
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='tutor',
        ),
    ]
