# Generated by Django 3.2.3 on 2021-12-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0002_lessonrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stutor.subject'),
        ),
    ]
