# Generated by Django 3.2.3 on 2021-12-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0002_languagechoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
        ),
    ]
