# Generated by Django 3.2 on 2021-06-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0003_auto_20210628_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='education_level_student',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject_student',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='education_level_tutor',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='subject_tutor',
            new_name='subject',
        ),
    ]
