# Generated by Django 3.2.3 on 2021-12-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
