# Generated by Django 3.2 on 2021-07-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0004_tutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tutor',
        ),
    ]
