# Generated by Django 3.2.3 on 2021-12-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0005_lessonrequest_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='lessonformat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stutor.lessonformat'),
            preserve_default=False,
        ),
    ]
