# Generated by Django 3.2.3 on 2021-12-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0006_lessonrequest_lessonformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='number_lessons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
