# Generated by Django 3.2.3 on 2021-12-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('stutor', '0006_openslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openslot',
            options={},
        ),
        migrations.AddField(
            model_name='openslot',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.tutor_account'),
        ),
    ]
