# Generated by Django 3.2.3 on 2021-12-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0007_auto_20211212_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='openslot',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stutor.subject'),
        ),
    ]
