# Generated by Django 3.2.3 on 2021-12-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('stutor', '0007_auto_20211222_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='student_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student_account'),
            preserve_default=False,
        ),
    ]
