# Generated by Django 3.2.3 on 2021-12-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0008_openslot_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stutor.subject'),
            preserve_default=False,
        ),
    ]
