# Generated by Django 3.2.3 on 2021-12-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('stutor', '0009_alter_openslot_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor_account'),
            preserve_default=False,
        ),
    ]
