# Generated by Django 3.2.3 on 2021-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutor', '0009_lessonrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('pending', 'Pending'), ('processed', 'processed')], default='open', max_length=255),
        ),
    ]
