# Generated by Django 3.2 on 2021-07-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor_account',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='tutor_account',
            name='subject',
        ),
    ]
