# Generated by Django 3.2 on 2021-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20210712_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaultprofilepicture.jpeg', null=True, upload_to='images/profile/'),
        ),
    ]
