# Generated by Django 3.2 on 2021-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_tutor_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaultprofilepicture.jpeg', null=True, upload_to=''),
        ),
    ]
