# Generated by Django 3.2.3 on 2021-12-22 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
        ('stutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='defaultprofilepicture.jpeg', null=True, upload_to='')),
                ('linked_tutors', models.ManyToManyField(to='tutor.tutor_account')),
                ('student_education_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stutor.education_level')),
                ('student_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stutor.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
