# Generated by Django 3.2 on 2021-10-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('stutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student_account',
            name='student_education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stutor.education_level'),
        ),
        migrations.AddField(
            model_name='student_account',
            name='student_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stutor.subject'),
        ),
        migrations.AddField(
            model_name='student_account',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
