# Generated by Django 3.2.3 on 2021-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_account',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='student name'),
        ),
    ]
