# Generated by Django 3.2 on 2021-10-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_account',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor_account'),
        ),
    ]
