# Generated by Django 3.2.3 on 2021-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_account',
            name='linked_tutors',
            field=models.ManyToManyField(to='student.Topping'),
        ),
    ]
