# Generated by Django 3.2 on 2021-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210712_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaultprofilepicture.jpeg', null=True, upload_to=''),
        ),
    ]
