# Generated by Django 3.2.3 on 2021-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('student', '0003_student_account_linked_tutors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_account',
            name='linked_tutors',
            field=models.ManyToManyField(to='tutor.tutor_account'),
        ),
    ]
