# Generated by Django 3.2 on 2021-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('student', '0003_student_account_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_account',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student_account',
            name='teacher',
            field=models.ManyToManyField(to='tutor.tutor_account'),
        ),
    ]
